#!/bin/sh

fancy_echo "Installing common applications..."
brew bundle --file=- <<EOF
# Browsers
cask "google-chrome"
cask "firefox"

# Docker
cask "docker"

# Slack
cask "slack"

# libpq for postgres connectivity without server
brew "libpq"
EOF

brew link --force "libpq"
